### ISSUE TITLE
Incorrect project name

### ISSUE THREAD

**Issue by oonis** [lordcrekit/JFileSynch#1]
I'm pretty sure what you meant was JFileSync. I've never seen Synchronization shortened to synch or sync

**Comment by lordcrekit** [comment]
No becouse with this, synchronization is a synch ;)

On Sep 1, 2017 09:25, "Sam Macaluso" <notifications@github.com> wrote:

I'm pretty sure what you meant was JFileSync. I've never seen
Synchronization shortened to synch or sync

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lordcrekit/JFileSynch/issues/1>, or mute the thread

**Comment by oonis** [comment]
Are you sure? It's pretty much agreed that's not the case, @lordcrekit.

https://en.oxforddictionaries.com/definition/sync

**Comment by lordcrekit** [comment]
Yeah also that name is already on maven so I can't take it xD

**Comment by oonis** [comment]
what maven? Are there files you didn't commit?

**Comment by lordcrekit** [comment]
Gradle is compatible with maven lol
